service: circusliving-amp-generate

provider:
  name: aws
  runtime: nodejs10.x
  logRetentionInDays: 14
  memorySize: 512
  reservedConcurrency: 5
  timeout: 600
  usagePlan: # Optional usage plan configuration
    quota:
      limit: 1000
      offset: 2
      period: MONTH
    throttle:
      burstLimit: 200
      rateLimit: 100

  deploymentBucket:
    name: sls.deploys # Overwrite the default deployment bucket, make your own name
    serverSideEncryption: AES256
  environment:
    DEPLOY_AUTH: auth
    NODE_ENV: ${self:provider.stage}
functions:
  generate:
    handler: sls/index.main
    events:
     - http: POST /
     - http: 'POST {proxy+}'

# package:
#   exclude:
#     - dist/**

custom:
    serverless-offline:
        port: 4000

plugins:
  - serverless-offline
