version: 2

_defaults: &defaults
  working_directory: ~/circus/amp
  parallelism: 1

jobs:
  build:
    <<: *defaults
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: aws cli
          command: |
            sudo apt-get -y install python-pip
            sudo pip install awscli
            sudo pip install awscli --upgrade
            sudo npm i -g serverless
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install deps
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules   
      - run:
          name: gen
          command: |
            if [ $CIRCLE_BRANCH == 'dev' ] || [ $CIRCLE_BRANCH == 'stg' ]
            then
              yarn gen:$CIRCLE_BRANCH
            else
              yarn gen
            fi
      - run:
          name: deploy
          command: |
            if [ $CIRCLE_BRANCH == 'dev' ] || [ $CIRCLE_BRANCH == 'stg' ]
            then
              yarn deploy:$CIRCLE_BRANCH
            else
              yarn deploy
            fi
      - run: 
          name: sls aws lambda deploy generate route
          command: |
            if [ $CIRCLE_BRANCH == 'dev' ] || [ $CIRCLE_BRANCH == 'stg' ]
            then
              yarn sls:deploy:$CIRCLE_BRANCH
            else
              yarn sls:deploy
            fi

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: /^(master|dev|stg)$/
