version: 2
orbs:
  aws-cli: circleci/aws-cli@0.1.16

_defaults: &defaults
  working_directory: ~/circus/amp
  parallelism: 1

jobs:
  aws:
    <<: *defaults
    steps:
      - aws-cli/setup
  build:
    <<: *defaults
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install deps
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules         
      - run:
          name: gen
          command: |
            if [ $CIRCLE_BRANCH == 'dev' ] || [ $CIRCLE_BRANCH == 'stg' ]
            then
              yarn gen:$CIRCLE_BRANCH
            else
              yarn gen
            fi
      - run:
          name: deploy
          command: |
            if [ $CIRCLE_BRANCH == 'dev' ] || [ $CIRCLE_BRANCH == 'stg' ]
            then
              yarn deploy:$CIRCLE_BRANCH
            else
              yarn deploy
            fi 

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - aws:
          context: aws
      - build:
          requires:
            - aws
          filters:
            branches:
              only: /^(master|dev|stg)$/
